### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [aquasecurity/aqua-dash#5]
Hi @sanjay-shah ,

What would you like to be added:

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.
Also i observed that screenshots are not uploaded in readme.md and showing 404 when clicking on image.

Why is this needed:

TOC is very useful to hop between the docs/info of the readme and avoids useless scrolling.

I would like to work on this, so do assign me

**Comment by sanjay-shah** [comment]
Appreciate your help in Creating TOC.

**Comment by ng29** [comment]
> Appreciate your help in Creating TOC.

Hey @sanjay-shah 

Here we go with TOC. .

**Comment by sanjay-shah** [comment]
Thanks @ng29

**Comment by ng29** [comment]
> Thanks @ng29

Just one query that am i eligible for **Aqua Security Hacktoberfest 2020**. ?
